Solve this system of equation using each of the four methods: REF, RREF, Matrix Inversion Method, Determinant Method. Verify the answers using emathhelp.net calculators or Python or Excel where possible. 


2x + y + z = 1

x + 2y – z = 8

3x – 2y + 2z = -7 

In [2]:
import numpy as np
from numpy.linalg import matrix_rank

In [3]:
x = np.mat(np.array([[2 ,1 ,1],[1 ,2 ,-1],[3,-2,2]]))
x

matrix([[ 2,  1,  1],
        [ 1,  2, -1],
        [ 3, -2,  2]])

In [4]:
matrix_rank(x)

3

In [3]:
import sympy
m = sympy.Matrix(x)
m_rref , n = m.rref()
print(n)
print(m_rref)

NameError: name 'x' is not defined

In [6]:
m_rref

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [7]:
x.I   ## matrix inverse

matrix([[-0.22222222,  0.44444444,  0.33333333],
        [ 0.55555556, -0.11111111, -0.33333333],
        [ 0.88888889, -0.77777778, -0.33333333]])

A = [[1,-1],[2,4]],

B = [[0,2],[1,3]],

C = [[1,2],[3,4]] are 2 x 2 matrices, i.e. 1 -1 is first row and 2 4 is second row etc.


a)Calculate A + B = [[1 , 1] , [3 , 7]]

b)Calculate A – C = [[0 ,-3],[-1 , 0]]

c)Calculate AT = [[1 , 2 ],[-1,4]]

d)Calculate A.A-1 

e)Calculate |A| = 4 + 2 = 6

f)Calculate Adjoint A = [[-4,-1],[2,-1]]


g)Calculate A-1 = ([[-2/3 ,-1/6] ,[1/3 , -1/6]]

h)Verify if AB = BA   AB!= BA

i)Verify if ABC = ACB


In [8]:
A = np.mat(np.array([[1,-1],[2,4]]))
B =np.mat(np.array([[0,2],[1,3]]))
C = np.mat(np.array([[1,2],[3,4]]))

In [9]:
print(A)
print('')
print(B)
print('')
print(C)

[[ 1 -1]
 [ 2  4]]

[[0 2]
 [1 3]]

[[1 2]
 [3 4]]


In [10]:
print(A + B)
print('')
print(A-C)
print('')
print(A.T)


[[1 1]
 [3 7]]

[[ 0 -3]
 [-1  0]]

[[ 1  2]
 [-1  4]]


In [11]:
A@A.I

## can't we use round(A@A.I)

matrix([[1.00000000e+00, 2.77555756e-17],
        [0.00000000e+00, 1.00000000e+00]])

In [12]:
A.I

matrix([[ 0.66666667,  0.16666667],
        [-0.33333333,  0.16666667]])

In [13]:
A.det = np.linalg.det(A)
print(A.det)
print(np.linalg.det(B))
print(np.linalg.det(C))

6.0
-2.0
-2.0000000000000004


In [14]:
adjA = A.det*A.I   

### we know that 
### A.inv = 1/A.det x (adj(A))  so use same to calculate adjoint so Adj[A] = A.det x A.inv 

In [15]:
AdjA = A.I * A.det

In [16]:
x = A@B

y = B@A
print(x)
print('')
print(y)



[[-1 -1]
 [ 4 16]]

[[ 4  8]
 [ 7 11]]


### so AB is not equal to BA

In [17]:
A@B@C

matrix([[-4, -6],
        [52, 72]])

In [18]:
x@C   ## se both gives same result.

matrix([[-4, -6],
        [52, 72]])

In [19]:
A@C@B

matrix([[ -2, -10],
        [ 20,  88]])

### so ABC is not equal to ACB

In [20]:
t = np.mat(np.array([[4,1],[-2,1]]))
t

matrix([[ 4,  1],
        [-2,  1]])

In [21]:
t.I

matrix([[ 0.16666667, -0.16666667],
        [ 0.33333333,  0.66666667]])

In [22]:
D = np.linalg.det(t)
D

6.0

In [23]:
D*t.I

matrix([[ 1., -1.],
        [ 2.,  4.]])

In [24]:
p =  np.mat(np.array([[2,-2],[4,3]]))

pdt = np.linalg.det(p)
p

matrix([[ 2, -2],
        [ 4,  3]])

In [25]:
adjp = p.I*pdt
adjp

matrix([[ 3.,  2.],
        [-4.,  2.]])

1)ystems of equations are solved by applying these rules. 

If |A| !=0, then consistent and unique solutions

•If |A|=0 and 

•(Adj A) B = 0, then consistent and has infinite solutions

•(Adj A) B != 0, then inconsistent 

•Use them to classify the following systems of equations.

2x - 3y = 5

4x - 6y = 10

In [26]:
a = np.mat(np.array([[2,-3],[4,-6]]))
a

matrix([[ 2, -3],
        [ 4, -6]])

In [27]:
det_a = np.linalg.det(a)
det_a

0.0

In [28]:
a.I ## this will show error of det.a is zero so inverse is zero

LinAlgError: Singular matrix

3)Following are some properties of matrices. Use 2x2 matrices and verify these using Python. Watch out, there could be some typos so when results do not match try to work out with both methods and be sure.

a)(AT)T = A

b)(A-1)-1 = A

c)(AB)-1  NOT EQUAL TO A-1 B-1

  (AB)-1   EQUAL TO B-1 A-1

d)(AB)T = BTAT YES IT IS EQUAL

e)(A + B)T = AT + BT  YES IT IS EQUAL

f)(AT) -1 = (A-1)T   YES IT IS EQUAL

g)A(Adjoint A) = (Adjoint A) A   YES IT IS EQUAL

h)A-1 = (1/Determinant of A) * Adjoint A   YES IT IS EQUAL TO

In [64]:
A.T.T

matrix([[ 1, -1],
        [ 2,  4]])

In [32]:
A

matrix([[ 1, -1],
        [ 2,  4]])

In [63]:
A.I.I

matrix([[ 1., -1.],
        [ 2.,  4.]])

In [34]:
(A@B).I

matrix([[-1.33333333, -0.08333333],
        [ 0.33333333,  0.08333333]])

In [62]:
B.I@A.I

matrix([[-1.33333333, -0.08333333],
        [ 0.33333333,  0.08333333]])

In [41]:
(A@B).T

matrix([[-1,  4],
        [-1, 16]])

In [42]:
B.T@A.T

matrix([[-1,  4],
        [-1, 16]])

In [43]:
(A.T).I

matrix([[ 0.66666667, -0.33333333],
        [ 0.16666667,  0.16666667]])

In [44]:
(A.I).T

matrix([[ 0.66666667, -0.33333333],
        [ 0.16666667,  0.16666667]])

In [45]:
(A + B).T

matrix([[1, 3],
        [1, 7]])

In [46]:
A.T + B.T

matrix([[1, 3],
        [1, 7]])

In [ ]:
x = Matrix(q).adjugate()
x

In [48]:
import sympy
from sympy import *

In [50]:
adjA = Matrix(A).adjugate()
adjA

Matrix([
[ 4, 1],
[-2, 1]])

In [51]:
A @ adjA

Matrix([
[6, 0],
[0, 6]])

In [52]:
adjA @ A

Matrix([
[6, 0],
[0, 6]])

In [53]:
A.I

matrix([[ 0.66666667,  0.16666667],
        [-0.33333333,  0.16666667]])

In [61]:
det_A = np.linalg.det(A)
det_A

6.0

In [60]:
(1/det_A)*adjA

Matrix([
[ 0.666666666666667, 0.166666666666667],
[-0.333333333333333, 0.166666666666667]])

4)Create a matrix M with order 3x3 and using sequence of numbers 1,2,3...9. In M, get the Minor and Cofactors of 2. Note: there may not be a method for this and you may have to use subset techniques in numpy the matrix.



5)Create a matrix of 3x3 using 1,2,3..6 and the last row has 9,9,9. Verify the determinant is zero.

In [65]:
d = np.array([1,2,3,4,5,6,9,9,9])


In [72]:
d0 = np.mat(d.reshape(3,3))
d0


matrix([[1, 2, 3],
        [4, 5, 6],
        [9, 9, 9]])

In [73]:
det = np.linalg.det(d0)
round(det)

-0.0

In [74]:
det

-3.996802888650562e-15

6)Verify that det(AB) = det(A)*det(B) 

yes it is equal

In [75]:
det_B = np.linalg.det(B)

In [77]:
det_AB = np.linalg.det(A@B)
det_AB

-12.0

In [78]:
det_A*det_B

-12.0

7)Given VT = [1,2] and B is a 2x2 = [[0,2],[1,3]]

Multiply and check the order of the results of VxB and BxV

In [81]:
V =np.mat([1,2])
V

matrix([[1, 2]])

In [84]:
B = np.mat([[0,2],[1,3]])
B

matrix([[0, 2],
        [1, 3]])

In [85]:
V@B

matrix([[2, 8]])

In [86]:
B@V   ## IT WILL NOT ALLOW BECAUSE SHAPE DOES NOT MATCH

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

2)Matrix A (3x3) has the following three rows [1,6,3], [5,2,4],[7,0,8]. Hand calculate these.
a)What is the Minor of 7?   18

b)What is the cofactor of 7?  18

c)Verify that the determinant is same when row 1 is expanded as column 1 is expended.  Both cases -98 , - 98

d)If row 1 is multiplied by 2 i.e. it is now [2,12,6] applying conceptual knowledge what do you now expect as determinant? Verify by calculating using Python. -196 det got twice 

e)If all the rows were 

In [87]:
w = np.mat([[1,6,3],[5,2,4],[7,0,8]])
w

matrix([[1, 6, 3],
        [5, 2, 4],
        [7, 0, 8]])

## Systematic practice MML

In [2]:
import numpy as np
import random
from sympy import Matrix

In [3]:
coeff = [2,1,1,1,1,2,-1,8,3,-2,2,-7]
mat = np.matrix(coeff).reshape(3,4)
print("Matrix:\n", mat)

# Method 1 - Using REF

print("\nRow Echelon Form:")
print("--------------------")
ref = Matrix(mat).echelon_form()
print("REF :\n",np.matrix(ref))
print("\nSolve the simplified equations obtained from REF method to obtain solutions\n")

# Method 2 - Using RREF

print("Reduced Row Echelon Form:")
print("--------------------------")
rref, n = Matrix(mat).rref()
print("RREF :\n", np.matrix(rref))
print("\nSolutions :",np.matrix(rref[:,-1].T))

# Method 3 - Using Matrix Inversion

print("\nMatrix Inversion Method:")
print("-----------------------------")
A = mat[:,:-1]
B = mat[:,-1]
print("X = Inv(A) * B")
print("\nInverse of A:\n",A.I)
print("\nB:\n",B)
print("\nSolutions :", np.matrix((A.I).dot(B)).T)

# Method 4 - Using Determinants

print("\nCramers Rule:")
print("-----------------------------")

values = []
values.append(np.linalg.det(A))
print("A:\n", A)
print("Det(A) = ",np.linalg.det(A))

Ax = np.append(B,A[:,[1,2]],axis=1)
values.append(np.linalg.det(Ax))
print("\nAx :\n", Ax)
print("Det(Ax) = ",np.linalg.det(Ax))

Ay = np.append(A[:,0],np.append(B,A[:,-1],axis=1),axis=1)
values.append(np.linalg.det(Ay))
print("\nAy :\n", Ay)
print("Det(Ay) = ",np.linalg.det(Ay))
                          
Az = np.append(A[:,[0,1]],B,axis=1)
values.append(np.linalg.det(Az))
print("\nAz :\n", Az)
print("Det(Az) = ",np.linalg.det(Az))

solutions = []
for i in range(3):
    solutions.append(float(values[i+1])/values[0])

print("\nSolutions :", np.matrix(solutions))

Matrix:
 [[ 2  1  1  1]
 [ 1  2 -1  8]
 [ 3 -2  2 -7]]

Row Echelon Form:
--------------------
REF :
 [[2 1 1 1]
 [0 3 -3 15]
 [0 0 -18 54]]

Solve the simplified equations obtained from REF method to obtain solutions

Reduced Row Echelon Form:
--------------------------
RREF :
 [[1 0 0 1]
 [0 1 0 2]
 [0 0 1 -3]]

Solutions : [[1 2 -3]]

Matrix Inversion Method:
-----------------------------
X = Inv(A) * B

Inverse of A:
 [[-0.22222222  0.44444444  0.33333333]
 [ 0.55555556 -0.11111111 -0.33333333]
 [ 0.88888889 -0.77777778 -0.33333333]]

B:
 [[ 1]
 [ 8]
 [-7]]

Solutions : [[ 1.  2. -3.]]

Cramers Rule:
-----------------------------
A:
 [[ 2  1  1]
 [ 1  2 -1]
 [ 3 -2  2]]
Det(A) =  -9.000000000000002

Ax :
 [[ 1  1  1]
 [ 8  2 -1]
 [-7 -2  2]]
Det(Ax) =  -8.999999999999998

Ay :
 [[ 2  1  1]
 [ 1  8 -1]
 [ 3 -7  2]]
Det(Ay) =  -17.999999999999996

Az :
 [[ 2  1  1]
 [ 1  2  8]
 [ 3 -2 -7]]
Det(Az) =  27.0

Solutions : [[ 1.  2. -3.]]


Solve this system of equation using each of the four methods: REF, RREF, Matrix Inversion Method, Determinant Method. Verify the answers using emathhelp.net calculators or Python or Excel where possible. 


2x + y + z = 1

x + 2y – z = 8

3x – 2y + 2z = -7 

In [10]:
coeff = [2 ,1,1,1,1,2,-1,8,3,-2,2,-7]
mat = np.mat(coeff).reshape(3,4)
print('matrix:\n ',mat)
print('\n')
print('_______________________________________________________________________________________________________________________')


## Method 1 using REF
print("Row echloan form ")
ref = Matrix(mat).echelon_form()
print('REF \n ' , np.matrix(ref))
print("by solving the above equation we got value of a = 1  , b = 2 , c = -3")
print('-----------------------------------------------------------------------------------------------------------------------')


## Method 2 using RREF
print("Reduced Row Echelon Form ")
rref , n  = Matrix(mat).rref()
print('RREF :\n ' ,np.matrix(rref))
print('\n solutions a ,b , c : \n', np.matrix(rref[:,-1].T))
print('\n')
print('-------------------------------------------------------------------------------------------------------------------')

# method 3 using matrix inversion
print('\n MATRIX INVERSION METHOD')
A = mat[: , :-1]
B = mat[: , -1]
print('A \n',A)
print('B \n ', B)
print( 'X = A(inv) * B')
print('solution\n' ,np.matrix((A.I).dot(B)).T)

print('----------------------------------------------------------------------------------------------------------------------')



matrix:
  [[ 2  1  1  1]
 [ 1  2 -1  8]
 [ 3 -2  2 -7]]


_______________________________________________________________________________________________________________________
Row echloan form 
REF 
  [[2 1 1 1]
 [0 3 -3 15]
 [0 0 -18 54]]
by solving the above equation we got value of a = 1  , b = 2 , c = -3
-----------------------------------------------------------------------------------------------------------------------
Reduced Row Echelon Form 
RREF :
  [[1 0 0 1]
 [0 1 0 2]
 [0 0 1 -3]]

 solutions a ,b , c : 
 [[1 2 -3]]


-------------------------------------------------------------------------------------------------------------------

 MATRIX INVERSION METHOD
A 
 [[ 2  1  1]
 [ 1  2 -1]
 [ 3 -2  2]]
B 
  [[ 1]
 [ 8]
 [-7]]
X = A(inv) * B
solution
 [[ 1.  2. -3.]]
----------------------------------------------------------------------------------------------------------------------


## cramers rule not understood

In [11]:
print("\nCramers Rule:")
print("-----------------------------")

values = []
values.append(np.linalg.det(A))
print("A:\n", A)
print("Det(A) = ",np.linalg.det(A))

Ax = np.append(B,A[:,[1,2]],axis=1)
values.append(np.linalg.det(Ax))
print("\nAx :\n", Ax)
print("Det(Ax) = ",np.linalg.det(Ax))

Ay = np.append(A[:,0],np.append(B,A[:,-1],axis=1),axis=1)
values.append(np.linalg.det(Ay))
print("\nAy :\n", Ay)
print("Det(Ay) = ",np.linalg.det(Ay))
                          
Az = np.append(A[:,[0,1]],B,axis=1)
values.append(np.linalg.det(Az))
print("\nAz :\n", Az)
print("Det(Az) = ",np.linalg.det(Az))

solutions = []
for i in range(3):
    solutions.append(float(values[i+1])/values[0])

print("\nSolutions :", np.matrix(solutions))


Cramers Rule:
-----------------------------
A:
 [[ 2  1  1]
 [ 1  2 -1]
 [ 3 -2  2]]
Det(A) =  -9.000000000000002

Ax :
 [[ 1  1  1]
 [ 8  2 -1]
 [-7 -2  2]]
Det(Ax) =  -8.999999999999998

Ay :
 [[ 2  1  1]
 [ 1  8 -1]
 [ 3 -7  2]]
Det(Ay) =  -17.999999999999996

Az :
 [[ 2  1  1]
 [ 1  2  8]
 [ 3 -2 -7]]
Det(Az) =  27.0

Solutions : [[ 1.  2. -3.]]


3)Following are some properties of matrices. Use 2x2 matrices and verify these using Python. Watch out, there could be some typos so when results do not match try to work out with both methods and be sure.

a)(AT)T = A

b)(A-1)-1 = A

c)(AB)-1  NOT EQUAL TO A-1 B-1

  (AB)-1   EQUAL TO B-1 A-1

d)(AB)T = BTAT YES IT IS EQUAL

e)(A + B)T = AT + BT  YES IT IS EQUAL

f)(AT) -1 = (A-1)T   YES IT IS EQUAL

g)A(Adjoint A) = (Adjoint A) A   YES IT IS EQUAL

h)A-1 = (1/Determinant of A) * Adjoint A   YES IT IS EQUAL TO

A =  [[1,-1],[2,4]]
 
B = [[0,2],[1,3]] 

C = [[1,2],[3,4]]

In [32]:
A = np.matrix([[1,-1],[2,4]])
B = np.matrix([[0,2],[1,3]])
C = np.matrix([[1,2],[3,4]])

print('A\n',A)
print('B\n', B)
print('C\n', C)
print('\n')

print('a)(AT)T = A')
print('')
print('(A.T).T = A \n', A.T.T)
print('A \n' , A)
print('--------------------------------------------------------------------------------------------------------------')

print('')
print('A-1)-1 = A')
print(' ')
print('(A.inv).inv \n' , A.I.I )
print('')
print('A\n',A)
print('-----------------------------------------------------------------------------------------------------------------')

print(' ')
print('(AB)-1 EQUAL TO B-1 A-1')
print('AB. INV = \n', (A@B).I)
print('')
print('B.INV .A.INV \n ' , B.I@A.I)
print('-----------------------------------------------------------------------------------------------------------------')

print(' ')
print('(AB)T = BTAT')
d = A@B
print('(AB).Transpose = \n',d.T)
print('')
print('B.Trans.A.Trans = \n ',(B.T)@(A.T))
print(' ')
print('--------------------------------------------------------------------------------------------------------------')

print('(A + B)T = AT + BT ')
w = A + B
print('(A+B).T \n', w.T)
print(' ')
print('A.T + B.T \n', A.T + B.T)
print(' ')
print('-------------------------------------------------------------------------------------------------------------')


print('')
print('(AT) -1 = (A-1)\n', (A.I).T)
print('')
print('(AT) -1 = \n',(A.T).I)
print('')
print('-------------------------------------------------------------------------------------------------------------')
print('')


A
 [[ 1 -1]
 [ 2  4]]
B
 [[0 2]
 [1 3]]
C
 [[1 2]
 [3 4]]


a)(AT)T = A

(A.T).T = A 
 [[ 1 -1]
 [ 2  4]]
A 
 [[ 1 -1]
 [ 2  4]]
--------------------------------------------------------------------------------------------------------------

A-1)-1 = A
 
(A.inv).inv 
 [[ 1. -1.]
 [ 2.  4.]]

A
 [[ 1 -1]
 [ 2  4]]
-----------------------------------------------------------------------------------------------------------------
 
(AB)-1 EQUAL TO B-1 A-1
AB. INV = 
 [[-1.33333333 -0.08333333]
 [ 0.33333333  0.08333333]]

B.INV .A.INV 
  [[-1.33333333 -0.08333333]
 [ 0.33333333  0.08333333]]
-----------------------------------------------------------------------------------------------------------------
 
(AB)T = BTAT
(AB).Transpose = 
 [[-1  4]
 [-1 16]]

B.Trans.A.Trans = 
  [[-1  4]
 [-1 16]]
 
--------------------------------------------------------------------------------------------------------------
(A + B)T = AT + BT 
(A+B).T 
 [[1 3]
 [1 7]]
 
A.T + B.T 
 [[1 3]
 [1 7]]
 
----------