In [2]:
import numpy as np

## 1] Solve using RREF and interpret (2 marks)

2x1 − 6x3 = −8 
x2 + 2x3 = 3 
3x1 + 6x2 − 2x3 = −4

Is this system of equations Consistent or Inconsistent?

If |A| !=0, then consistent and unique solutions

•If |A|=0 and 

•(Adj A) B = 0, then consistent and has infinite solutions

•(Adj A) B != 0, then inconsistent 

In [3]:
A = np.mat([[2,0,-6],[0,1,2],[3,6,-2]])
print(A)
print('\n')
detA = np.linalg.det(A)
print('detA = ' , abs(detA))  
print('|detA| !=0, then consistent and unique solutions')

[[ 2  0 -6]
 [ 0  1  2]
 [ 3  6 -2]]


detA =  9.999999999999998
|detA| !=0, then consistent and unique solutions


## [2] What is the rank of this matrix? (2 Marks)
3 / 2 / 1 / 9 / 0

5	3	0

1	2	-4

-2	-4	8

In [4]:
A = np.array([[5,3,0],[1,2,-4],[-2,-4,8]])
print('A = \n' ,A)
print('\n Rank of Matrix ')
print(np.linalg.matrix_rank(A))

A = 
 [[ 5  3  0]
 [ 1  2 -4]
 [-2 -4  8]]

 Rank of Matrix 
2


# 3] Verify Independence of the following vectors (2 Marks)

u	v	w

1	3	0

2	2	4

3	1	8

The vectors are independent / dependent / Neither

In [5]:
from numpy import *
a = array([[1,3,0,0],[2,2,4,0],[3,1,8,0]] , dtype =float)
## define matrix
## Get Rows and Columns
rows = shape(a)[0]
cols = shape(a)[1]
## solution vector to store solutions
x = zeros(cols-1)
## print matrix here
print(a)
print('rows is ',rows)
print('column is ',cols)
print('\n')
## forwarding algorithm here 
for i in range(cols-1):
    for j in range(i+1 , rows):
        a[j ,:]= -(a[j,i]/a[i,i])*a[i , :] + a[j ,:]
       
 ### prining matrix in row echelon form
print('\n row echelon form \n' , a)

### Backsubstitution of algorithm 
for i in arange(rows-1,-1,-1):
    x[i] = (a[i ,-1]-a[ i ,0:cols-1]@x)/a[i , i]
print('\n final answer')
print(x)
print(' [a, b, c ]')

[[1. 3. 0. 0.]
 [2. 2. 4. 0.]
 [3. 1. 8. 0.]]
rows is  3
column is  4



 row echelon form 
 [[ 1.  3.  0.  0.]
 [ 0. -4.  4.  0.]
 [ 0.  0.  0.  0.]]

 final answer
[nan nan nan]
 [a, b, c ]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in double_scalars


### We do not got a , b , c =0 to be linearly independent but we neither got a ,b, c as some value 
### So lets calculate dot product of any two vectors 
### if a.b != 0 then vectors are neither dependet or independence


In [6]:
a = np.array([1,2,3])
b = np.array([3,2,1])
print('a.b = ',np.dot(a,b))
print('so a.b != 0 then vectors are neither dependet or independence')

a.b =  10
so a.b != 0 then vectors are neither dependet or independence


# [4] Find Basis Vectors of the subspace spanned by the following  (2 Marks)

U1 = [1,2,2-1]

U2 = [1,3,1,1]

U3 = [1,5,-1,5]

U4 = [1,1,4,-1]

U5 = [2,7,0,2]

### We first put these in array/matrices and then take transpose of it to form matrices)

In [15]:
mat = np.matrix([[1,2,2,-1],[1,3,1,1],[1,5,-1,5],[1,1,4,-1],[2,7,0,2]])
print(mat)
print('\n',mat.T)
print("Reduced Row Echelon Form:")
rref, n = Matrix(mat.T).rref()
print("RREF :\n", np.matrix(rref))


[[ 1  2  2 -1]
 [ 1  3  1  1]
 [ 1  5 -1  5]
 [ 1  1  4 -1]
 [ 2  7  0  2]]

 [[ 1  1  1  1  2]
 [ 2  3  5  1  7]
 [ 2  1 -1  4  0]
 [-1  1  5 -1  2]]
Reduced Row Echelon Form:
RREF :
 [[1 0 -2 0 1]
 [0 1 3 0 2]
 [0 0 0 1 -1]
 [0 0 0 0 0]]


#### We Can clearly see that in  RREF Column 1 , 2 ,4 has pivots so these are our  basis For the Subspace Spanned by the Given Vectors
#### So column or vector U1 = [1,2,2-1] ,U2 = [1,3,1,1]  ,U4 = [1,1,4,-1] 
#### are our  Basis For the Subspace Spanned by the Given Vectors

# [5] Calculate the L1 and L2 Norms of this vector 		(2 Marks)
## [-4, 3, 0, 2, -1, 5]

#### L2 Norm is sqrt of sum of squares of values = sqrt(a**2 + b**2 + c**2 + ...........)
#### L1 Norm is sum of absolute values  = |a| + |b| |c| + |d| + .........

In [8]:
x = -4*-4 + 3*3 + 0*0 + 2*2 + -1*-1 +5*5
L2 = np.sqrt([x])
print('L2 Norm' , L2)
L1 = abs(-4) + abs(3)+abs(0)+abs(2)+abs(-1)+abs(5)
print('L1 Norm', L1 )

L2 Norm [7.41619849]
L1 Norm 15


In [9]:
L = [-4,3,0,2,-1,5]
i = 1
for i in L:
    L2 = sqrt(i*i)
    print(L2)

4.0
3.0
0.0
2.0
1.0
5.0


# [6] What will [4,2] from [1,0], [0,1] basis to a new basis of [2,0] and [0,2]? 	 (2 Marks)


NewVector  = Inv(New Basis).Old Basis.Oldvector

old = ([1,0],[0,1]).[4,2] 



In [21]:
U = np.matrix([[1,0],[0,1]])
v = np.array([[4],[2]])
print(' old Basis\n', U ,'\n')
print('\n old Vector\n ', v,'\n')
New_Basis = np.matrix([[2,0],[0,2]])
print('new basis\n' , New_Basis)
inv_NB = New_Basis.I
print('\n NewVector = Inv(New Basis).Old Basis.Oldvector')
NewVector = inv_NB*U*v
print('\n new Vector \n' ,NewVector)

 old Basis
 [[1 0]
 [0 1]] 


 old Vector
  [[4]
 [2]] 

new basis
 [[2 0]
 [0 2]]

 NewVector = Inv(New Basis).Old Basis.Oldvector

 new Vector 
 [[2.]
 [1.]]


## [7] Compute the L and U components of this matrix (4 Marks)


6	-2	 0

9	-1	 1

3	 7	 5

Select the option that matches the calculated L and U  matrices.

L has a row 0.5, 4, 1 and U has a row with 0, 0, 1

## LU Decomposition

In [11]:
from sympy import Matrix
from sympy import init_printing
init_printing()

A = Matrix([[6,-2,0],[9,-1,1],[3,7,5]])
print('Given Matrix in question is A = ')
A


Given Matrix in question is A = 


⎡6  -2  0⎤
⎢        ⎥
⎢9  -1  1⎥
⎢        ⎥
⎣3  7   5⎦

In [12]:
L , U , _ = A.LUdecomposition()
print('lower triangle')
L ## Lower Triangle

lower triangle


⎡ 1   0  0⎤
⎢         ⎥
⎢3/2  1  0⎥
⎢         ⎥
⎣1/2  4  1⎦

In [13]:
print('upper triangle')
U ## Upper Triangle

upper triangle


⎡6  -2  0⎤
⎢        ⎥
⎢0  2   1⎥
⎢        ⎥
⎣0  0   1⎦

In [14]:
print('\n')
print('A == L*U is ', A == L*U , 'Hence Varified')



A == L*U is  True Hence Varified
